---
- name: Install ClickHouse
  hosts: clickhouse
  become: true
  roles:
    - clickhouse
  tags: clickhouse

- name: Install Vector
  hosts: vector
  become: true
  roles:
    - vector-role
  tags: vector

- name: Install Lighthouse
  hosts: lighthouse
  become: true
  roles:
    - lighthouse-role
  tags: lighthouse
