[tox]
minversion = 3.25.1
envlist =
    molecule-ubuntu24
    molecule-rocky9

[testenv]
deps =
    ansible>=2.10
    molecule
    molecule-plugins[docker]
    docker
    ansible-lint
commands =
    molecule test -s {env:SCENARIO:default}

[testenv:molecule-ubuntu24]
setenv =
    SCENARIO = ubuntu24

[testenv:molecule-rocky9]
setenv =
    SCENARIO = rocky9
